server:
  port: 8088

spring:
  application:
    name: test-config-server
  profiles:
    active: native

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: INFO
    org.springframework.data: INFO
    org.springframework: INFO
    test: INFO
    net.ttddyy.dsproxy.listener: DEBUG
    root: INFO

management:
  endpoint:
    health:
      show-components: always
